# Generated by Django 3.2 on 2024-11-21 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appTrigorojo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='categoria',
            table='categoria',
        ),
    ]
