# Generated by Django 3.2 on 2024-11-21 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appTrigorojo', '0002_alter_categoria_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='categoria',
            table='categorias',
        ),
    ]
